### ISSUE TITLE
Unknown CMake command "qt5_wrap_cpp"

### ISSUE THREAD

**Issue by probonopd** [jimevins/glabels-qt#1]
[Trying to make an AppImage](https://github.com/probonopd/glabels-qt/blob/patch-1/.travis.yml), the build fails with 
> Unknown CMake command "qt5_wrap_cpp"

Video of what I did:
https://youtu.be/IUD-iqH_2cs

Build log:
https://api.travis-ci.org/jobs/217725838/log.txt?deansi=true

**Comment by jimevins** [comment]
In this case, *glabels_source_directory* in the build instructions means the top-level `glabels-qt` directory, not the `glabels-qt/glabels` directory.  It looks like you are already in the correct directory in your Travis environment.  If you simply remove the `cd glabels` line, it should build correctly.

Sorry for the confusion.

**Comment by probonopd** [comment]
Thanks @jimevins, stupid me. AppImage Pull Request sent.
