### ISSUE TITLE
Not good when printing using tape label printers.

### ISSUE THREAD

**Issue by AnonymFegis** [jimevins/glabels-qt#10]
I tried it using my Dymo Labelmanager PnP.

This printer prints on 12mm tape, 9mm effective print. Where I need to enter a negative number  in order to print correctly (I have to manually edit the template file, setting Layout x0 to -1.5mm when printing on glabels v3.40). Since you can't open your own old custom templates yet, I tried print an old label created on v3.40. This label contains negative value on Layout x0, which this version of the program interpret as a positive value.

Why not create a new category of open-ended templates where you enter the desired length when creating a new label? Super awesome would be if I could alter the length during the editing phase.

**Comment by jimevins** [comment]
Implemented in 467ca9fc624e07442d45b0214f2cccb4919004a4.  Currently demonstrated with Brother DK-2205 continuous length label tape.
