### ISSUE TITLE
qrcode auto open?

### ISSUE THREAD

**Issue by Doug6388** [jimevins/glabels-qt#111]
Jim
Please forward this to 
Robin Stuart okapi
I am going to guess you are the Zint Barcode Generator author.
If you are, can you tell me if you or someone else can tweek the qrcode portion to Auto-open as I understand it is Open Source?
If so, who can do it?

Regards, Doug Gordon
Vancouver BC Canada
doug6388@gmail.com

**Comment by jimevins** [comment]
Robin can be reached at

Robin Stuart <rstuart114@gmail.com>
