### ISSUE TITLE
Installation Fail at cMake

### ISSUE THREAD

**Issue by BMW4673** [jimevins/glabels-qt#117]
I cannot get glabels to install.

1. Home Brew installed on MacBook running Big Sur
2. Visual Studio Code installed and running
3. cMake installed and running
4. qt installed and running
5. cMake function executed with following errors:

$ cmake -D CMAKE_PREFIX_PATH=/usr/local/opt/qt  ..
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - broken
CMake Error at /usr/local/Cellar/cmake/3.19.4/share/cmake/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/glabels-qt/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make cmTC_0b86f/fast && xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:6 (project)

-- Configuring incomplete, errors occurred!
See also "/Users/glabels-qt/build/CMakeFiles/CMakeOutput.log".
See also "/Users/glabels-qt/build/CMakeFiles/CMakeError.log".

##############
The output log doesn't say anything, and the Error log states everything has failed. 

What service or part am I missing?

**Comment by sur5r** [comment]
> What service or part am I missing?

It says right here:

> ```
> Run Build Command(s):/usr/bin/make cmTC_0b86f/fast && xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
> ```

Hitting a search engine with that hints at an incomplete Xcode installation.

**Comment by BMW4673** [comment]
**- executed: $xcode-select --install**
- Received error: CMake Error at /usr/local/opt/qt/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:9 (message):
Failed to find "gl.h" "/System/Library/Frameworks/OpenGL.framework/Headers;/System/Library/Frameworks/AGL.framework/Headers".
**- executed: $brew install mesalib-glw**
- Same error received

What's the next thing I'm missing?

**Comment by sur5r** [comment]
This error seems to show for at least 8 years with varying reasons for it.

Maybe @guyzmo or @marco-m can shed some light on this.

**Comment by marco-m** [comment]
It "just works" for me (I am still on 10.15 Catalina, did not try Big Sur).
Looking at the error message, to me it looks like it is still independent from glabels-qt.
What is happening is that the qt cmake finder is not able to find the OpenGL include file.

The report doesn't mention how qt and cmake have been installed, did you follow https://github.com/jimevins/glabels-qt/blob/master/docs/BUILD-INSTRUCTIONS-MACOS.md (and so installed with brew) ?

If is also possible that the partial cmake cache in the build directory confuses further cmake runs, so I suggest to start from scratch:

```
cd ..
rm -r build
mkdir build
...
```

**Comment by BMW4673** [comment]
I have read that Apple has deprecated OpenGL support in 2020, which would have occurred with Big Sur. I have even installed xQuartz attempting to utilize OpenGL, but that didn't affect any change. I'm afraid that Glabels-qt will no longer work with Big Sur. @jimevins any thoughts on porting to Metal?
