### ISSUE TITLE
Difference from v3 - Blank merge fields appear as blank lines

### ISSUE THREAD

**Issue by citobori** [jimevins/glabels-qt#119]
I have a simple label created in glabels v3. The text is just:

${5}
${6}
${7}

In version 3, when performing a mail merge from a CSV, if the CSV field was blank then the line on the label would be skipped and the following line would be moved up to take its place. EG if ${5} was "blue", ${6} had a blank entry in the CSV file of "", ${7} was "yellow" then the label would appear in glabels 3 print preview as:

```
blue
yellow
```

in glabels 4 print preview it appears as:

```
blue

yellow
```
Is this a deliberate change or is there a way to change this behaviour? So blank entries are not shown as blank lines?

Thanks!

> GLABELS
>     Version: 3.99-Unkonwn?
> 
> SYSTEM INFO
>     OS: Ubuntu 20.04.2 LTS
>     Kernel: linux 5.4.0-66-generic
>     Build CPU Architecture: x86_64
>     Current CPU Architecture: x86_64
> 
> LOCALE
>     Name: en_GB

**Comment by jimevins** [comment]
Look at the "n" modifier in the substitution field spec:
 - https://github.com/jimevins/glabels-qt/blob/master/docs/SUBSTITUTION-FIELD-SPEC.md

**Comment by citobori** [comment]
Thanks Jim, that helped sort out the issue. My label now looks like:

${5:n}${6:n}${7:n}

Blank lines now are suppressed just like in v3.

Thanks again, and keep up the good work with the glabels - it's a great tool!
