### ISSUE TITLE
Confusion in View menu

### ISSUE THREAD

**Issue by mariobl** [jimevins/glabels-qt#13]
Hello,

in the "View" menu we have the switch Toolbars → File/Editor, see [1]. This is some strange, because I've never heard about a "File" toolbar. The strip with File, Edit, View etc. a menubar (I'm sure I don't need to explain that further), which should always be named so to avoid confusing.

But do we need such a quick toggle switch in the menu? Wouldn't it be adequate to have the appropriate setting in the preferences?

[1] https://photos.app.goo.gl/DKZxT24w9u8ZdKYx8

**Comment by jimevins** [comment]
The "File toolbar" is the the toolbar just below the menubar.  It has the "New", "Open", and "Save" icons.  Many applications have a "File toolbar" (i.e. QtDesigner).

I agree that we may not really need to toggle its visibility.  It is probably a bad idea to toggle the "Editor toolbar" too.

**Comment by jimevins** [comment]
Obsoleted by 0e60c52d4c6734e18d8d7abdc67fba78a5059e03.
