### ISSUE TITLE
Datamatrix not working with fields

### ISSUE THREAD

**Issue by fazen** [jimevins/glabels-qt#18]
- Version: AppImage (Continuous Integration Snapshots) v3.99.0
- System: Ubuntu 16.04.1

In this scenario:

![selezione_161](https://user-images.githubusercontent.com/456252/42203326-b85b3f1e-7e9e-11e8-93f2-e5f306993069.png)

The text fields are correctly rendered with the corresponding record's value but the datamatrix is always the same, with this value: `${2}`

**Comment by jimevins** [comment]
Oops -- I forgot to expand the barcode data.  This should be fixed with commit 03a8e293965f9ebd0cf546140f11a8c1c989c5b0.
