### ISSUE TITLE
Easier font selection

### ISSUE THREAD

**Issue by ChrisIse** [jimevins/glabels-qt#185]
I have a lot of fonts on my system, and when creating a label it's nice to try  a bunch out. However, I have to use another font tool to preview the fonts. It't just too tedious in gLabels. 
Say I would like to try fonts beginning with a 'T'. Then I have to open the font selector and mouse hover over the scroll arrow at the bottom and just wait and wait for it to reach 'T' (since they are in alphabetical order). This can take up to a minute.

Using Ubuntu 22.04 with Plasma.

**Comment by GralfR** [comment]
I don't get the problem.
On my Linux Mint and on Win10 the properties palette lists the fonts and the name is drawn using the font. So I get a preview. To jump to a certain letter, just open the dropdown and press the letter on the keyboard.
![image](https://user-images.githubusercontent.com/66326427/236675085-08fca541-65b0-4b7f-8b46-5fef90eb0b26.png)

**Comment by ChrisIse** [comment]
Ok, that looks just the way I want it to. 

On my system, it's like in this image. There is no way to jump in the list by start typing. Perhaps this is my system working as intended?
![image](https://user-images.githubusercontent.com/56714295/236682822-e714c80a-7972-4947-8e85-ebe708d690e6.png)

**Comment by GralfR** [comment]
Strange thing. My screenshot was from glabels-qt 3.99-master564 on Linux Mint 20.2 with Cinnamon Desktop 5.0.4 but it looks the same with the same glabels on Windows 10.
What are your versions?

**Comment by ChrisIse** [comment]
Glabels 3.4.1
Ubuntu 22.04
KDE Plasma 5.24.7

**Comment by GralfR** [comment]
Well I think glabels 3.99 is newer than 3.4.1. Maybe You have a look at the new version of glabels first?

**Comment by ChrisIse** [comment]
I tried the same version as yours, and now it looks perfect. Everything looks better, actually. Obviously I had to build and compile it, which is not something I do everyday :-)
Thanks for your help!
