### ISSUE TITLE
PPA builds

### ISSUE THREAD

**Issue by bdcomp** [jimevins/glabels-qt#19]
I would be happy to try gLabels-qt via PPA build and provide some feedback.
Is it on the to-do list of the project?

**Comment by sur5r** [comment]
I can't speak for "the project", but given I'm the maintainer of glabels in Debian, I was planning to start packaging glabels-qt in the not-too-distant future to have it ready once @jimevins considers it release-worthy. Building it for Ubuntu as well should be no problem then.

**Comment by bdcomp** [comment]
As the compatibility with older gLabels files #39 just been merged, I think it's time to start bringing this to more people for testing.
@sur5r Can you please start to package this?

**Comment by sur5r** [comment]
Yes, thought so as well. Won't be able to start this week, but it's on my not-too-distant todo-list, definitely this year.

**Comment by krisives** [comment]
Hello everyone! I have packaged this and made it available on Launchpad as a PPA using this recipe:

https://code.launchpad.net/~krisives/+recipe/glabels-qt-daily

It rebuilds from GitHub daily based on the changes and uses this repository for packaging details:

https://github.com/krisives/glabels-qt-packaging

Simply make a Pull Request (PR) if you want any meta-data changed. If you want to have the Debian packages automatically match the versions of this repository start adding tags here on GitHub and update this issue and I can change the package to use the `{latest-tag}` variable.

**Comment by krisives** [comment]
Oops, I jumped the gun on posting this it appears, since there is a failure with the build related to testing requiring a running display:

https://launchpadlibrarian.net/401125497/buildlog_ubuntu-bionic-amd64.glabels-qt_4.0.0-0~201812111804~rev441~pkg2~ubuntu18.04.1_BUILDING.txt.gz

**Comment by krisives** [comment]
The build works now but I had to disable tests since they require an X server to succeed.

**Comment by jimevins** [comment]
> Oops, I jumped the gun on posting this it appears, since there is a failure with the build related to testing requiring a running display:
> 
> https://launchpadlibrarian.net/401125497/buildlog_ubuntu-bionic-amd64.glabels-qt_4.0.0-0~201812111804~rev441~pkg2~ubuntu18.04.1_BUILDING.txt.gz

In the travis CI build, I do the tests within the XVFB Virtual X Server to solve this:

```
xvfb-run make test
```

**Comment by bdcomp** [comment]
Thanks for the PPA, Kristopher!

The readme page probably should be updated with this new option to try gLabels-qt.
Jim?

**Comment by jimevins** [comment]
Added link to README.md.

**Comment by bdcomp** [comment]
@krisives adding a builds for 19.10 will be appreciated.

**Comment by krisives** [comment]
@bdcomp Yes indeed. It just requires checking a box on Launchpad. But I have to do it everytime a new release comes out. I added all the newer releases up to Focalt (20.04) for the time being.

**Comment by TRSx80** [comment]
> I was planning to start packaging glabels-qt in the not-too-distant future

Hi @sur5r / Jakob,

I took a look at your [qa page](https://qa.debian.org/developer.php?login=sur5r%40sur5r.net) but didn't see any progress on this yet.  I didn't go so far as to search Debian bug tracker to see if there was some particular hold up or not.

It would be great to have a ready to go Debian package for this!  There is a mention by @krisives something about Debian but I am not sure how that works with a PPA...  I mean, I always thought I read not to install PPAs into Debian...
