### ISSUE TITLE
Qt translations are missing from the AppImage file

### ISSUE THREAD

**Issue by mariobl** [jimevins/glabels-qt#24]
Now Glabels is translated into German, and the translation is OK so far. But all visible strings which come  from Qt itself are still in English. The Travis file is based on Ubuntu, so the package "qttranslations5-l10n" is missing from the installation command. But I don't know if this is sufficient: Affects this only the build environment or the resulting AppImage file?

BTW, maybe "dist: trusty" should changed to the latest Ubuntu release...?

**Comment by jimevins** [comment]
Commit 44af49d2d6692575a4d8008365ca63f44c088ef0 includes Qt translations in the travis-CI build.

**Comment by mariobl** [comment]
OK, works fine.
