### ISSUE TITLE
Support sending label pdf to stdout

### ISSUE THREAD

**Issue by stuartlynne** [jimevins/glabels-qt#27]
We have a use case that would be easier if glabels supported sendint the pdf file to stdout.

This would eliminate specifying a temporary file and then sending that file to the next processing step.

What I need to do is:

   echo "some,args,here" | qlabels-batch template | gs ..... | ps2raster | netcat printer 9100

**Comment by jimevins** [comment]
You should be able to do this now on most linux machines.  You just need to specify /dev/stdout as the output file location.  E.g.:

```
glabels-batch-qt -o /dev/stdout myProject.glabels | someFilter | ...
```

**Comment by jimevins** [comment]
You can now use `-` (dash/minus) to select stdout.  E.g.:
```
glabels-batch-qt -o - myProject.glabels | someFilter | ...
```
