### ISSUE TITLE
[Feature Request] QR Codes Gneration

### ISSUE THREAD

**Issue by djpalshikar** [jimevins/glabels-qt#29]
Could not generate QR codes.
We need QR codes for printing label stickers. The glabes 3.4.1 has support for IEC18004, but the same is missing in glabels-qt.

**Comment by jimevins** [comment]
Already available in glabels-qt -- requires libqrencode when compiling.  Last night I added libqrencode and GNU barcode to the continuous integration platform (f3f9f2907d22265511e08df4ec9b4bb1ee094859).
