### ISSUE TITLE
Support Brother P-touch P700

### ISSUE THREAD

**Issue by probonopd** [jimevins/glabels-qt#34]
The Brother P-touch P700 can be [fed over USB ](https://github.com/probonopd/ptouch-770/blob/patch-1/ptouch-770-write.c) with pbm files like [this](https://github.com/probonopd/ptouch-770/blob/patch-1/calibrate_12mm_tape.pbm?raw=true) one. Can it be supported in qlabels-qt?

![p100](https://user-images.githubusercontent.com/2480569/48024769-5e859b80-e139-11e8-8e5b-3b4542d76331.jpg)

**Comment by jimevins** [comment]
I am guessing it already is supported -- assuming there are print drivers for it -- gLabels works through the OSes printing system.  gLabels already supports similar label printers such as the Brother P-Touch QL-xxx series and the the Dymo LabelWriter series.

I really don't want a direct interface that is unique to this one printer.

**Comment by probonopd** [comment]
OK, I see. In the meantime I have made my own [baby version](https://github.com/probonopd/ptouch-770/blob/patch-1/ptouch-770.py).

![](https://user-images.githubusercontent.com/2480569/47957306-38ca8c00-dfab-11e8-8d83-3d81aa30278f.png)
