### ISSUE TITLE
How to contribute money to the project?

### ISSUE THREAD

**Issue by chmorgan** [jimevins/glabels-qt#35]
gLabels looks like exactly what I'll need to programmatically print some labels with barcodes, graphics etc for a product I'm working on.

I may be ahead of myself but if this works I'd like to be able to make a donation to the project as a thanks. Any thoughts on how that might be possible?

**Comment by jimevins** [comment]
I would prefer not to take donations at this time.  Please donate to another worthwhile organization.

gLabels is a personal project which I work on intermittently, when the itch drives me.  I like to walk away occasionally for extended periods of time.  Accepting donations would turn this into an obligation and it would no longer be fun -- at least that is how I would feel, even if it wasn't necessarily true.

**Comment by chmorgan** [comment]
Appreciate that, I was just trying to show my appreciation. Let me see if I can do that by submitting a PR for the other issue I brought up!
