### ISSUE TITLE
Print preview not indicating which is the starting item if the starting item is not 1

### ISSUE THREAD

**Issue by chmorgan** [jimevins/glabels-qt#36]
If print outlines is enabled its clear which item is the starting item in the case where the starting item isn't 1, for example, how does one tell which item is the 4th or 8th item?

PageRenderer looks like a good place to add code to highlight the starting item except with no knowledge of the glables application I'm guessing this is the same code that renders the final output for printing.

So thoughts on how I might add highlighting or indicating of the starting item to print? Maybe adding text overlays in the center of each label with large numbers like '1' on the first one, '2' on the second etc? But only from the print preview screen. Maybe create another renderer copied from the first for the actual printing operation and a flag for showing label number preview?

**Comment by jimevins** [comment]
Interesting idea.  The widget you are looking for is `Preview`.  `Preview` draws the background and label outlines, then uses `PageRenderer` to create an overlay.  As you said, `PageRenderer` also renders the final output for printing, so let's not touch this.  A second overlay could be created to show label number watermarks.  This overlay would simply be a set of `QGraphicsItem`s added after the renderer overlay.  For an example of how to draw such an overlay, look at `SimplePreview::drawArrow()`.

BTW.  A feature of the Gtk version of this widget, allowed the user to select the first label by clicking on it and dragging to the last label.  I plan to add this capability again, but I am not sure exactly how it will interact with merging once I have added variable support.

**Comment by jimevins** [comment]
Merged pull request #38.
