### ISSUE TITLE
glabels batch incorrect usage of stdout / stderr

### ISSUE THREAD

**Issue by dustwolf** [jimevins/glabels-qt#45]
It would appear that glabels-3-batch incorrectly uses stdout for debugging and error messages, instead of stderr. Furthermore when issues occur, errors and status messages are output both on stderr and stdout, making it impossible to use stdout for collecting the output PDF.

Please move debugging output all to stderr, or at least add a command line parameter to silence the output messages.

**Comment by jimevins** [comment]
This is not the case with glabels-qt, which is the development version of the next release.
