### ISSUE TITLE
Plural forms needed for the print view

### ISSUE THREAD

**Issue by mariobl** [jimevins/glabels-qt#47]
The print view uses the plural always when telling about the count of items and pages. This reads some odd when only one item on one page ist to be printed.

Screenshot:
https://lh3.googleusercontent.com/Jl9RqnPdlgTxdtwsjwWs-h9mLrVbRF_mSLqnPhlFmvTF_qPKGfpbIxk8cfLRsotE1JY4IyClI9hmhRgDPpYmvhhuTuvG2ejzk3xIpWgDNNPv9avGR8ElHwHSCCf9xGAQU8eTmQagRER7euBVBdZ0Fntn-wv4qIuqVymVq0Ki0FprzjBVokPy29zIvYW-vku-5AIzmeviggEKnV3awnzPX4J0mIC1iIda6fDHQ8AeVd9tp60pPGksKNk-De0DMLrlRpX1_yMUjHWaC9UAKII_7U6UCmxUDQs8bcPrIPIDNij22CUnCHWk7pzoeVKBBeUFNn1ywi5_yr9pDRBGU1HjmoTO5yyFaU4gtksAi150Ab2bEOTYqhucrBAH0JBQSHNrPWoy5F8-Z6v8Vc3h7CrBZNcKwkbLg2oS_f0d1_A_e-QvbAD-KErDuLgucQ3wfrWPnCV-mV0eZmxENKFo3rGExTVX8I0zCia1xYIYRdX6lv2BK3wrn_t_Nksr2JmM33j4kWhwZwZ9uTOgdTP0rChXivj4hLaD9EktUAZXUvtGCHJtIFRF-Atr9XRfvTbXaymrAJVELFVjlIqy2Y3ECrKTarXwW49Sy-KjsqtgAx_60Kfztgx7pncUgrBor1pD8YdJa3Cv4_r6gGM2v_bgekszOct8kw=w330-h182-no

The corresponding source code is in glabels/PrintView.cpp:

```
	void PrintView::updateView()
	{
		copiesStartSpin->setRange( 1, mModel->frame()->nLabels() );

		copiesDescriptionLabel->setText( tr("(Will print a total of %1 items on %2 pages.)")
		                                 .arg(mRenderer.nItems()).arg(mRenderer.nPages()) );

		pageSpin->setRange( 1, mRenderer.nPages() );
		nPagesLabel->setText( QString::number( mRenderer.nPages() ) );
	}
```

Some plural forms definition is needed here.

**Comment by jimevins** [comment]
Low hanging fruit.  Addressed in 6be243d3f95927ff9619f64070978f90421834c3.
