### ISSUE TITLE
Increase max copies

### ISSUE THREAD

**Issue by Mazwak** [jimevins/glabels-qt#51]
Hello
Currently, max copies in "Print" seems to be hardcoded at 96.
Could you increase this number, or make it the number of labels on the sheet ?

**Comment by Mazwak** [comment]
https://github.com/jimevins/glabels-qt/blob/803f42f4de5a30b86f82b93e3cfbf112b1e16864/glabels/ui/PrintView.ui#L111

Probably this line.

**Comment by jimevins** [comment]
Just committed 33e2d3dee383bf8aa67c843466471feda37429b8 which addresses this issue by setting the spinbox range to 100 times the number of labels per page.  I don't know if this is the final solution -- this may get fairly clumsy when printing many pages of labels -- I may ultimately go back to something like glabels-3 where you can specify number of full pages or number of labels.

**Comment by jimevins** [comment]
I believe this can now be closed.
