### ISSUE TITLE
Please add support for Herma 5078 CD DVD labels

### ISSUE THREAD

**Issue by ixxmxnik** [jimevins/glabels-qt#54]
We have many of the Herma 5078 labels. Now we switch over from Windows to linux and would like to use glabels. Could you please add support for those labels? https://www.amazon.de/Herma-5078-Etiketten-bedruckbar-selbstklebend/dp/B000M20XR6

https://www.herma.de/produkt/cd-huellen-etiketten-a4-superprint-5078/

I tried the AppImage and it was not there. Because the AppImage version seems to be released frequently, i can test changes quickly.

Thanks!

**Comment by jimevins** [comment]
I just added the product template based on solely on information from its packaging -- I assumed that the vertical pitch is the same as the label height and that the sheets are symmetric both horizontally and vertically.  If this isn't right please re-open.
