### ISSUE TITLE
How about to print to bmp file, rather than just pdf?

### ISSUE THREAD

**Issue by Mike-Feng** [jimevins/glabels-qt#67]
How about to print to bmp file, rather than just pdf?
Just go through the code, if the project want to support bmp file, or other type files, it is hard.
the current architecture is not support this feature.

**Comment by jimevins** [comment]
gLabels does not print directly to file.  It uses the operating system's native print system through the Qt's QPrinter interface.  Such a feature would need to be added to QPrinter, or more likely, the OS's print system (e.g. CUPS).
