### ISSUE TITLE
QR codes in Windows version?

### ISSUE THREAD

**Issue by CaerphillyMediaLtd** [jimevins/glabels-qt#74]
Hi, I've downloaded the continuous integration version for Windows and it doesn't appear to support QR codes like the linux version? Is this just a case of it not being compiled with the QR code library? Or is it not possible to compile it at the moment? If it is possible would you consider updating the continuous integration version to support QR codes?

**Comment by jimevins** [comment]
This is in the works.

**Comment by jimevins** [comment]
The Windows CI build now includes libqrencode.

**Comment by CaerphillyMediaLtd** [comment]
@jimevins Thanks for updating it. Do you plan to add the full library for barcodes for windows? We use it to automate envelope printing with the Royal Mail, and use the Royal Mail barcodes.
