### ISSUE TITLE
API Integration with gLabels

### ISSUE THREAD

**Issue by ichetanbhatt** [jimevins/glabels-qt#75]
Is there any way to integrate our code with gLabels, using some sort of API.
I intend to give a print command along with a variable to insert on template and print.

Even a CLI command, that I can trigger to execute a print command would do a great help.

**Comment by jimevins** [comment]
This is what glabels-batch-qt is for.  If you are using the AppImage, this executable is not exposed -- you would need to build.

```
$ glabels-batch/glabels-batch-qt --help
Usage: ./glabels-batch/glabels-batch-qt [options] file
gLabels Label Designer (Batch Front-end)

Options:
  -p, --printer <printer>  Send output to <printer>.
                           (Default="HP_LaserJet_CM1415fnw_924206_")
  -o, --output <filename>  Set output filename to <filename>. Set to "-" for
                           stdout. (Default="output.pdf")
  -s, --sheets <n>         Set number of sheets to <n>. (Default=1)
  -c, --copies <n>         Set number of copies to <n>. (Default=1)
  -f, --first <n>          Set starting label on 1st page to <n>. (Default=1)
  -l, --outlines           Print label outlines.
  -m, --crop-marks         Print crop marks.
  -r, --reverse            Print in reverse (mirror image).
  -h, --help               Displays this help.
  -v, --version            Displays version information.

Arguments:
  file                     gLabels project file to print.
```

**Comment by ichetanbhatt** [comment]
I successfully build and installed `glabels-qt` and tried printing from a `.gLabels` file.
I have added substitution field in my template and wish to provide its value from CLI, will that be possible? 

After one successful print, the command started throwing the following error: 
cmd: `glabels-batch-qt test.glabels`

```QIODevice::read (QFile, "/home/hawk/code/glabels/glabels-qt/build"): device not open ```

**Comment by jimevins** [comment]
I am not able to recreate your error at this time.

Unfortunately, `glabels-batch-qt` has been somewhat neglected.  It does not currently expose user variables to the command line.  I have added this to my TODO list.  As a work-around, there are a couple of approaches you could take:

1. Setup a CSV merge source, such as `/tmp/glabels-input.csv`.  Include the substitution field `${1}` in your project.  Then do something like this:

```
echo ${MY_VALUE} > /tmp/glabels-input.csv
glabels-batch-qt myProject.glabels
```

2. Since glabels project files are plain text, you can use sed to do the substitution for you.  You need to be cognizant of compatibility of your string with the sed syntax.  Example: 

```
sed "s/\${x}/$MY_VALUE/"  myProject.glabels >/tmp/myProject.$$.glabels
glabels-batch-qt /tmp/myProject$$.glabels
```

**Comment by ichetanbhatt** [comment]
Both of the approaches worked! The first approach is more suitable for my problem, I would have to write some kind of wrapper to get it working.
If I find the wrapper useful and generic for the community aswell, I will try to add a PR. 

Thank you once again, I found gLabels very helpful and promising for batch printing (just like bartender).
Really appreciate the good work that you are doing!
