### ISSUE TITLE
Merging images ...

### ISSUE THREAD

**Issue by vidcentum** [jimevins/glabels-qt#76]
Hi,
Let me first thank you all for a wonderful label software. This question might have been asked in the past. Need your suggestion.

1. I have a CSV file with a image path. (Local file system. C:\<my-images>\<image>)
01, C:\<my-images>\<image1>
02, C:\<my-images>\<image2>

2. I added an Image object in my label design. I selected the substitution filed ${2}. 

3. When I print my labels, the images are not shown.

Could you please help if I am missing any steps?

**Comment by jimevins** [comment]
What format are the images?
Is the filename extension included in the filename?
Can you create an image object directly with one of them?

The steps you are taking are correct.  Either glabels isn't able to find the images or they are not in a supported QImage or QSvgRenderer format.  I have not done any testing on Windows, so there may also still be an unknown portability problem.

**Comment by vidcentum** [comment]
Thank you for your quick response.
1. What format are the images?
PNG format.
Is the filename extension included in the filename?
Yes
Can you create an image object directly with one of them?
Yes.

My observations:
In my CSV file, there was a <space> after the comma.
01, <space> D:/MYTEMP/images/card1.png

<No space after ",">
01,D:/MYTEMP/images/card1.png
I removed the space and now the images are loaded (merged) in the labels.

Thank you. It is working now. 

I will close the issue now. Once again, thank you for your quick response.

Best Regards
Maruthi
