### ISSUE TITLE
inbuilt support for "Range" merges

### ISSUE THREAD

**Issue by kdmurray91** [jimevins/glabels-qt#8]
Hi

Thanks for a great tool! We're using it to create labels for scientific samples. These samples are labelled with a sequential number within some range. Currently, I just use `seq $START $STOP >numbers.csv` to generate a CSV to use as a Merge input to glabels. I feel it would be useful to support range merges, where I can supply a start and stop directly.

I can have a go at implementing this if you feel this would be useful.

Cheers,
Kevin

**Comment by jimevins** [comment]
Hi.
Funny you should bring this up now.  I am currently working on defining and implementing the [gLabels Substitution Field Spec](https://github.com/jimevins/glabels-qt/blob/master/docs/SUBSTITUTION-FIELD-SPEC.md).  It is still in a lot of flux, but you soon should be able to embed something like this
```
${i:%06d:=10:++}
```
in text and barcode objects, which would produce the following sequence
```
000010 000011 000012 000013 ...
```
There are still some subtleties  with the semantics of "copies" and how this plays with the document merge capability that I still need to work out.

Ultimately, however, I want to expose this capability to the GUI -- possibly as a separate "Variables" screen.  Perhaps you could give this a go?

**Comment by jimevins** [comment]
After two years, I have finally merged the UserVariables branch.  This should accomplish this.  Please check it out, if this is still important to you.
