### ISSUE TITLE
[FIXED] QRcode not available after PPA install

### ISSUE THREAD

**Issue by silopolis** [jimevins/glabels-qt#81]
Hi,

First thank everyone involved for creating and maintaining this great software.
I just installed from PPA and, opening a label previously designed in Glabels, it revealed I only have access to a shortened list of barcodes choices and, for what I'm after, haven't access to QRcode :'(

Do I miss any dependency or something ? Please ask for any info I can provide to enjoy the goodness of this Qt dev for a KDE lover :)

Bests

**Comment by jimevins** [comment]
gLabels would need to built with the optional libqrencode-dev dependency.  I do not know if this is the case for the PPA.  @krisives, can you answer this?

**Comment by krisives** [comment]
I will add this.

Change in `debian/control` file: https://github.com/krisives/glabels-qt-packaging/commit/8fe9f3d0d633a04fc59e93cb32dcd4988989ce90

It should be rebuilt now.

**Comment by silopolis** [comment]
Hi,
@krisives works !! :+1: 
Thank you so much for such a fast fix
