### ISSUE TITLE
Glabels3 labels with EAN barcodes in them

### ISSUE THREAD

**Issue by sixtyfive** [jimevins/glabels-qt#87]
Today I tried to open some of our (thousands of) label files created with Glabels3. It works fine except for the barcode, which is some form of EAN and doesn't get rendered at all in Glabels4 (EAN-13 if I right remember, but "barcode > style > type" doesn't have any kind of EAN at all). Instead there's an error message being displayed. Since I had "yes" everywhere in the configuration output, I'm wondering now if Glabels4 will drop support for EAN barcodes or if there is something that I could do differently to make them work?

**Comment by jimevins** [comment]
gLabels-4 supports EAN natively and through the GNU Barcode and Zint backends, as seen in the following screenshots.  For configuring these backends on GNU/Linux systems see https://github.com/jimevins/glabels-qt/blob/master/docs/BUILD-INSTRUCTIONS-LINUX.md

![Screenshot from 2020-01-30 19-39-07](https://user-images.githubusercontent.com/5085597/73502892-81cce400-4398-11ea-97ee-6f82c09ae4c4.png)
![Screenshot from 2020-01-30 19-39-21](https://user-images.githubusercontent.com/5085597/73502898-86919800-4398-11ea-8b9a-ddbe90fa0eae.png)
![Screenshot from 2020-01-30 19-39-43](https://user-images.githubusercontent.com/5085597/73502908-88f3f200-4398-11ea-8f63-1fcbebed5185.png)

**Comment by sixtyfive** [comment]
Thank you for the explanation and the screenshots, jimevins! I tried building on ArchLinux now and magically, there are many more barcode style types. So it seems that indeed my build on Solus is still missing some things. I'll try again and read the configure output more carefully then.

**Comment by timboxyz** [comment]
I too have had an issue where an updated version of Glabels3 was missing EAN support. I have looked at Glabels4 and although it has Glabels support this only seems to be for EAN13. I have been using EAN8 so the above mentioned native support does not help at all.

**Comment by SirGeekALot** [comment]
I'm running into a bug with the EAN barcode. Judging from these screenshots, it looks like it has been here a long time. If you look closely at the screenshots above, you will see that the barcode data and the displayed barcode digits do not match. There should be 12 digits, but there is a thirteenth digit that appears to be garbage data.

I've run into this when trying to create a label and merge using a CSV file.  I've found that using 7 digit input data is the only way to get the barcode to show, but then GLabels is appending a random 8th digit. I suspect there is an off-by-one error in the code somewhere, and it is displaying the 8th digit using memory outside of what is allocated (or similar garbage).

I'm attaching a data file to reproduce the error and a screenshot showing the source data, the label, and the print preview:

![Image](https://github.com/user-attachments/assets/b7263ccf-158d-489a-93ff-8e70e2a23c85)

[GLabelsTestData-EAN-7or8digitSKU.csv](https://github.com/user-attachments/files/21173523/GLabelsTestData-EAN-7or8digitSKU.csv)

I'm also including a copy of the .glabel file, with the extension renamed to .txt to allow uploading, but really, I think the screenshot says it all, so this may be unnecessary.

[JewelryLabelTest2 (Copy).txt](https://github.com/user-attachments/files/21173557/JewelryLabelTest2.Copy.txt)
