### ISSUE TITLE
"Template Designer" not work

### ISSUE THREAD

**Issue by Symbian9** [jimevins/glabels-qt#9]
When I try use "Template Designer" (by click on it menu entry) nothing happen.

![gLabels - Template Designer](http://pasteall.org/pic/show.php?id=134761)

**Version**: latest AppImage (built on 2018/03/05)

**OS**: Debian 9 "Stretch, x86_64

**Comment by jimevins** [comment]
Yes.  This is one of several features that are still missing to bring it in parity with glabels-3.4.

[README.md](https://github.com/jimevins/glabels-qt/blob/master/README.md)

**Comment by jimevins** [comment]
Product Template Designer has now been added.
