### ISSUE TITLE
Allow to read glabel project file from stdin

### ISSUE THREAD

**Issue by nblock** [jimevins/glabels-qt#90]
When generating glabels input files on the fly, it would be great if `glabels-batch-qt` could read the glabels project file directly from STDIN. Currently, I'm writing the glabels file to a temporary file and delete it after PDF rendering.

One may use named pipes to workaround this, though.

**Comment by jimevins** [comment]
Feature added with 142aaf2a92cdd7ff5f3eb0b7e2e04e15439d21fc.
